/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // frontend: [{ type: "autogenerated", dirName: "frontend" }],
  "react-next": [{ type: "autogenerated", dirName: "frontend/react-next" }],
  "js-ts": [{ type: "autogenerated", dirName: "frontend/js-ts" }],
  "html-css": [{ type: "autogenerated", dirName: "frontend/html-css" }],
  learning: [{ type: "autogenerated", dirName: "learning" }],
};

module.exports = sidebars;
